version: "3"
services:
  db:
    image: mariadb:10.6.4-focal
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data_production:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-wordpress}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_USER:-wordpress}
    expose:
      - 3306
      - 33060
    networks:
      - wp
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PORT:-8080}:90"
    environment:
      PMA_HOST: ${WORDPRESS_DB_HOST:-db}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
    networks:
      - wp
  wordpress:
    image: wordpress:latest
    ports:
      - "${PORT:-8000}:80"
    restart: always
    depends_on:
      - db
    volumes: ["./html:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
    networks:
      - wp
networks:
  wp:
volumes:
  db_data_production:
