name: DIGITALOCEAN_DEPLOY
on:
  push:
    branches: [main]
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - name: Create .env file
        run: echo 'PORT=${{secrets.PORT}}' > .env
      - name: Run docker compose up build
        run: docker-compose up -d

