name: DIGITALOCEAN_DEPLOY
on:
  push:
    branches: [main]
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Create .env
        run: echo 'PORT=${{secrets.PORT}}' > .env
      - name: Run docker compose up build
        run: docker-compose up -d
